version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: second-opinion-postgres
    environment:
      POSTGRES_DB: secondopinion
      POSTGRES_USER: second_opinion_user
      POSTGRES_PASSWORD: second_opinion_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - second-opinion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U second_opinion_user -d secondopinion"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: second-opinion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - second-opinion-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: second-opinion-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@secondopinion.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - second-opinion-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  second-opinion-network:
    driver: bridge