apiVersion: 1

datasources:
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.54.0"
      cacheLevel: "High"
      disableMetricsLookup: false
      customQueryParameters: ""
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          urlDisplayLabel: "View Trace"

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - key: "service_name"
            value: "service"
        mappedTags:
          - key: "service_name"
            value: "service"
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: "service_name"
            value: "service"
        queries:
          - name: "Sample query"
            query: "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le))"
      nodeGraph:
        enabled: true
      search:
        hide: false
      spanBar:
        type: "Tag"
        tag: "http.path"

  # Elasticsearch datasource for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logs-*"
    editable: true
    jsonData:
      index: "logs-*"
      timeField: "@timestamp"
      esVersion: "8.15.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
      includeFrozen: false
      xpack: false

  # Loki datasource for log aggregation (alternative to Elasticsearch)
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          label: "trace_id"
          url: "http://localhost:16686/trace/${__value.raw}"
          datasourceUid: jaeger
        - name: "ServiceName"
          label: "service_name"
          url: ""
          datasourceUid: ""

  # TestData datasource for development/testing
  - name: TestData
    type: testdata
    uid: testdata
    access: proxy
    editable: true
    isDefault: false

  # Alertmanager datasource for alert management
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: "prometheus"

  # InfluxDB datasource (if needed for time-series data)
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: "secondopinion"
    user: "admin"
    editable: true
    jsonData:
      version: "InfluxQL"
      maxSeriesPerQuery: 1000000
      defaultBucket: "secondopinion"
      organization: "second-opinion"
      defaultRetentionPolicy: "autogen"
    secureJsonData:
      password: "admin123"

deleteDatasources:
  - name: "Old Prometheus"
    orgId: 1